---
title: "Schiedea hookeri/kaalae RIMs"
author: "[John Powers](http://sites.uci.edu/powers/)"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: no
    lib_dir: libs
    code_folding: hide
    toc: yes
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r setup, message = FALSE}
library(tidyverse)
library(RColorBrewer)

library(glmmTMB)
library(broom)
library(emmeans)

library(knitr)
knitr::opts_chunk$set(comment="", cache=T, warning = F, message = F, fig.path = "figures/", dev = "svglite", fig.width=5, fig.height=4, width=999)
options(digits=4, knitr.kable.NA = "") # for kables

load("data/rims_data.rda")

sxc.labels <- set_names(c("K intrapop", "K interpop", "K x H", "H x K", "H interpop", "H intrapop"), sxc.levels)
F1.col <- set_names(c(brewer.pal(3,"Greens")[2:3],brewer.pal(9,"Oranges")[5], brewer.pal(9,"Set1")[7], brewer.pal(3,"Purples")[3:2]), sxc.levels)
```

# Datasets

```{r datasets}
traits %>% filter(generation !="P") %>% select(c(generation,ylab, yvar, data, type)) %>% kable
```

# F1 Generation

## Sample sizes

```{r sampsize}
F1 <- set_names(datanames[1:6]); F1[[6]] <- "inflobiomass.sum"

map_dfr(F1, ~ tally(get(.)), .id="dataset") %>% 
  pivot_wider(names_from=dataset, values_from=n) %>% kable(caption="F1 datasets totals")

map_dfr(F1, ~ tally(group_by(get(.), crosstype, momsp, dadsp)), .id="dataset") %>% 
  pivot_wider(names_from=dataset, values_from=n) %>% kable(caption="F1 datasets by crosstype and species")

map_dfr(F1, ~ tally(group_by(get(.), crosstype, momsp, dadsp, mompop, dadpop)), .id="dataset") %>% 
  pivot_wider(names_from=dataset, values_from=n) %>% kable(caption="F1 datasets by crosstype and population")
```

## Models

Expand this code to see the model specifications:

```{r models}
F1.mod <- list(
  firstflower =          glmmTMB(firstflower ~          sxc +           (1|mompid) + (1|dadpid), data=survflr),
  firstinflo.biomass.g = glmmTMB(firstinflo.biomass.g ~ sxc + collect + (1|mompid) + (1|dadpid), data=survflr),
  inflo.biomass.g =      glmmTMB(inflo.biomass.g  ~     sxc + collect + (1|mompid) + (1|dadpid), data=inflobiomass.sum),
  flower.number =        glmmTMB(flower.number  ~       sxc + collect + (1|mompid) + (1|dadpop), data=inflobiomass.sum),#dadpid model prob.
  veg.biomass.g =        glmmTMB(veg.biomass.g ~        sxc + collect + (1|mompid) + (1|dadpid), data=vegbiomass),
  total.per.anther =     glmmTMB(total.per.anther ~     sxc +           (1|mompid) + (1|dadpid), data=pollen),
  viable.per.anther =    glmmTMB(viable.per.anther ~    sxc +           (1|mompid) + (1|dadpid), data=pollen),
  viable.seeds =         glmmTMB(viable.seeds ~         sxc +           (1|mompid) + (1|dadpop), data=filter(seeds, viable.seeds>0),
                                 family="truncated_nbinom1"),
  prop.germ =            glmmTMB(prop.germ      ~ sxc + (1|mompid) + (1|dadpid), family="betabinomial", data=germination, weights = planted),
  alive =                glmmTMB(alive          ~ sxc + (1|mompid) + (1|dadpop), family="betabinomial", data=survflr),#dadpid model prob.
  flowered =             glmmTMB(flowered       ~ sxc + (1|mompid) + (1|dadpid), family="betabinomial", data=filter(survflr, alive)),
  prop.viable =          glmmTMB(prop.viable    ~ sxc + (1|mompid) + (1|dadpid), family="betabinomial", data=pollen, weights = total),
  capsule.formed =       glmmTMB(capsule.formed ~ sxc + (1|mompid) + (1|dadpop), family="betabinomial", data=seeds))
#TODO try to find dadpid for seeds
```

## Inference 

```{r inference}
F1.test <- map_dfr(F1.mod, ~car::Anova(.) %>% tidy(), .id="trait") 
F1.test %>% left_join(traits %>% filter(generation=="F1") %>% select(trait=yvar, step)) %>% 
  arrange(step) %>% select(-step) %>% 
  mutate(term=recode(term, sxc = "cross", collect= "collection date"),
         trait = recode(trait, !!!set_names(traits$ylab[-1], traits$yvar[-1])) %>% 
               str_remove(fixed(" (g)")),
         p.value=format(p.value,digits=2)) %>% 
  kable(digits=1, caption="ANOVA of GLMM (Type III Wald chisquare tests)")
  
F1.emm <-  map_dfr(F1.mod, ~emmeans(., ~sxc) %>% summary(type="response") %>%  #average over collect date
                             tidy %>% rename(estimate=any_of(c("response","prob"))), .id="trait") 
```

## Plots

```{r f1plot}
plot_F1 <- function(emm, data, yvar, ylab, type="continuous") {
  data <- get(data)
  if(type=="continuous") {
    p <- ggplot(data, aes_string(y=yvar, x="sxc", fill="sxc")) +
      geom_violin(draw_quantiles = (1:3)/4) + 
      geom_pointrange(data=filter(emm, trait==yvar), aes(y=estimate, ymax=conf.high, ymin=conf.low)) + 
      scale_fill_manual(values=F1.col) + guides(fill="none") +
      scale_y_continuous(name = ylab, expand = expansion(mult=c(0, 0.05)), limits=c(0,NA))
  } else if(type=="binary") {
    p <- data %>% drop_na(all_of(yvar)) %>% 
      group_by(sxc, mompop, dadpop) %>% summarize(across(all_of(yvar), ~sum(.)/n()), n=n(), .groups="drop") %>% 
      ggplot(aes_string(y=yvar, x="sxc", color="sxc")) +
      geom_point(size=4)+
      geom_pointrange(data=filter(emm, trait==yvar) %>% 
                        mutate(conf.low  = ifelse(conf.high-conf.low>0.9,NA,conf.low), 
                               conf.high = ifelse(conf.high-conf.low>0.9,NA,conf.high)), 
                      aes(y=estimate, ymax=conf.high, ymin=conf.low), color="black") + 
      scale_color_manual(values=F1.col) + guides(color="none") +
      scale_y_continuous(ylab, limits=c(0,1), labels=~scales::percent(.,accuracy=1))
  }
  p <- p + scale_x_discrete("Cross", labels = sxc.labels) + 
    theme_minimal() + theme(panel.grid.major.x = element_blank())
  print(p)
}

traits %>% filter(generation=="F1") %>% select(data, yvar, ylab, type) %>% 
  pwalk(plot_F1, emm=F1.emm)
```

## Flower biomass regression

```{r infloreg}
ggplot(inflobiomass, aes(x=inflo.biomass.g, y=flrs, color=cross)) + 
  geom_point() +  geom_smooth(method="lm", se=F) +  
  geom_rug(data=inflobiomass.sum, aes(x=inflo.biomass.g/inflo, y=10), sides="b") + 
  scale_x_log10() + scale_y_log10() + 
  scale_color_manual(values=set_names(F1.col, c("KKwithin","KK", "KH", "HK", "HH", "HHwithin"))[-c(1,6)]) +
  theme_minimal() + labs(y="Flower number", x="Inflorescence biomass (g)", color="Cross")

ggplot(inflobiomass, aes(x=inflo.biomass.g, y=flrs/inflo.biomass.g, color=cross)) + 
  geom_point() +  geom_smooth(se=F) +  
  scale_x_log10() + scale_y_continuous() + 
  scale_color_manual(values=set_names(F1.col, c("KKwithin","KK", "KH", "HK", "HH", "HHwithin"))[-c(1,6)]) +
  theme_minimal() + labs(y="Flowers per g biomass", x="Inflorescence biomass (g)", color="Cross")

ggplot(inflobiomass.sum, aes(y=inflo, x=sxc, fill=sxc)) +
  geom_boxplot() + 
  scale_fill_manual(values=F1.col) + guides(fill="none") +
  scale_y_continuous("Inflorescences", expand = expansion(mult=c(0, 0.05)), limits=c(0,NA))+
  scale_x_discrete("Cross", labels = sxc.labels) + 
  theme_minimal() + theme(panel.grid.major.x = element_blank())

ggplot(inflobiomass.sum, aes(y=inflo.biomass.g/inflo, x=sxc, fill=sxc)) +
  geom_boxplot() + 
  scale_fill_manual(values=F1.col) + guides(fill="none") +
  scale_y_continuous("Biomass per inflorescence (g)", expand = expansion(mult=c(0, 0.05)), limits=c(0,NA))+
  scale_x_discrete("Cross", labels = sxc.labels) + 
  theme_minimal() + theme(panel.grid.major.x = element_blank())

ggplot(inflobiomass.sum, aes(y=flower.number/inflo, x=sxc, fill=sxc)) +
  geom_boxplot() + 
  scale_fill_manual(values=F1.col) + guides(fill="none") +
  scale_y_continuous("Flowers per inflorescence", expand = expansion(mult=c(0, 0.05)), limits=c(0,NA))+
  scale_x_discrete("Cross", labels = sxc.labels) + 
  theme_minimal() + theme(panel.grid.major.x = element_blank())

```

## Fitness and RI

```{r fitness, fig.width=6}
F1.emm %>%  left_join(traits %>% filter(generation=="F1") %>% select(trait=yvar, step)) %>% arrange(step) %>% 
  mutate(est.se = paste(round(estimate,2.5-log10(estimate)), "\U00B1", round(std.error,2.5-log10(estimate))),
                  trait = recode(trait, !!!set_names(traits$ylab[-1], traits$yvar[-1])),
                  sxc = recode(sxc, !!!sxc.labels)) %>% 
  select(trait, sxc, est.se) %>% pivot_wider(names_from = sxc, values_from=est.se) %>% 
  kable(caption="Absolute fitness components")

F1.RI <- F1.emm %>% separate(sxc, into=c("momsp","crosstype")) %>% 
  filter(crosstype !="within", trait != "firstflower") %>% #TODO firstflower is backwards fitness
  select(trait, momsp, crosstype, estimate) %>% pivot_wider(names_from=crosstype, values_from=estimate) %>% 
  rowwise() %>% mutate(across(c(between,hybrid), ~ ./max(between,hybrid)),
                       RI = 1 - 2 *  hybrid/(hybrid + between)) %>% 
    left_join(traits %>% filter(generation=="F1") %>% select(trait=yvar, step)) %>% arrange(step) %>% 
      mutate(trait = recode(trait, !!!set_names(traits$ylab[-1], traits$yvar[-1])) %>% 
               str_remove(fixed(" (g)")) %>% factor() %>% fct_reorder(step)) 
  
F1.RI %>% select(-step) %>% 
  pivot_wider(names_from=momsp, values_from=c(between, hybrid, RI)) %>% 
  select(trait, KK = between_kaal, KH = hybrid_kaal, K_RI=RI_kaal, HH = between_hook, HK = hybrid_hook, H_RI=RI_hook) %>% 
  kable(caption="Relative fitness components between hybrids and their maternal parent, and RI from Sobel & Chen 2014", digits=3)

ggplot(F1.RI, aes(y=fct_rev(trait), x=RI, color=momsp)) + 
  geom_vline(xintercept=0, linetype=2) + geom_vline(xintercept=-1)+ geom_vline(xintercept=1)+ 
  geom_point(shape=17, size=2) +
  scale_color_manual(values = set_names(F1.col[c(2,5)], c("kaal","hook")), labels=c("S. kaalae","S. hookeri")) +
  scale_x_continuous(limits=c(-1.1,1.1), breaks=c(-1,-0.5,0,0.5,1),
                     labels=c("-1\nheterosis","-0.5","0\nno\nbarrier","0.5","1\ncomplete\nisolation")) + 
  theme_minimal() + theme(legend.position = "top", legend.text = element_text(face="italic"))+
  labs(x="Reproductive isolation", y="Fitness component", color="Maternal parent")
```

# F2 Generation

## Sample sizes

```{r f2sampsize}
F2 <- set_names(datanames[7:10])

map_dfr(F2, ~ tally(get(.)), .id="dataset") %>% 
  pivot_wider(names_from=dataset, values_from=n) %>% kable(caption="F2 datasets totals")

map_dfr(F2, ~ tally(group_by(get(.), generation, momdadcross)), .id="dataset") %>% 
  pivot_wider(names_from=dataset, values_from=n) %>% kable(caption="F2 datasets by cross")
```

## Models

```{r f2models}
F2.mod <- list(
  seed.mass.mg =         glmmTMB(seed.mass.mg ~      momdadcross, data=f1seedmass),
  total.per.anther =     glmmTMB(total.per.anther ~  momdadcross, data=f2pollen),
  viable.per.anther =    glmmTMB(viable.per.anther ~ momdadcross, data=f2pollen),
  viable.seeds =         glmmTMB(viable.seeds ~      momdadcross, data=filter(f1seeds, viable.seeds>0), family="truncated_nbinom1"),
  prop.viable =          glmmTMB(prop.viable ~       momdadcross, family="betabinomial", data=f2pollen, weights = total),
  capsule.formed =       glmmTMB(capsule.formed ~    momdadcross, family="betabinomial", data=f1seeds))
```


## Inference

```{r f2inference}
F2.test <- map_dfr(F2.mod, ~car::Anova(.) %>% tidy(), .id="trait") 
F2.test %>% left_join(traits %>% filter(generation=="F2") %>% select(trait=yvar, step)) %>% 
  arrange(step) %>% select(-step) %>% 
  mutate(trait = recode(trait, !!!set_names(traits$ylab[-1], traits$yvar[-1])),
         p.value=format(p.value,digits=2)) %>% 
  kable(digits=1, caption="ANOVA of GLMM (Type III Wald chisquare tests)")
  
F2.emm <-  map_dfr(F2.mod, ~emmeans(., ~momdadcross) %>% summary(type="response") %>%  
                             tidy %>% rename(estimate=any_of(c("response","prob"))), .id="trait") 
```


## Plots

### All crosses

```{r f2plot}
momdadcross.levels <- c("H x H","H x HK","H x KH","H x K","HK x H","HK x HK","HK x KH","HK x K","KH x H","KH x HK","KH x KH","KH x K","K x H","K x HK","K x KH","K x K")
momdadcross.labels <- momdadcross.levels %>% str_replace_all("\\s","\n") %>% set_names(momdadcross.levels)

plot_F2 <- function(emm, data, yvar, ylab, type="continuous") {
  data <- get(data) %>% mutate(momdadcross = factor(as.character(momdadcross), levels=momdadcross.levels))
  if(type=="continuous") {
    p <- ggplot(data, aes_string(y=yvar, x="momdadcross", fill="momcross")) + 
      geom_violin(draw_quantiles = (1:3)/4) + 
      geom_pointrange(data=filter(emm, trait==yvar) %>% 
                        separate(momdadcross, into=c("momcross","dadcross"), sep=" x ", remove=F) %>% 
                        mutate(momdadcross = factor(as.character(momdadcross), levels=momdadcross.levels)),
                      aes(y=estimate, ymax=conf.high, ymin=conf.low),color="black") + 
      scale_fill_manual(values=set_names(F1.col[2:5],c("K","KH","HK","H")))+
      guides(fill="none") +
      scale_y_continuous(name = ylab, expand = expansion(mult=c(0, 0.05)), limits=c(0,NA))
  } else if(type=="binary") {
    p <- ggplot(data, aes_string(y=yvar, x="momdadcross", color="momcross")) + 
      geom_pointrange(data=filter(emm, trait==yvar) %>% 
                        separate(momdadcross, into=c("momcross","dadcross"), sep=" x ", remove=F) %>% 
                        mutate(momdadcross = factor(as.character(momdadcross), levels=momdadcross.levels)) %>% 
                        mutate(conf.low  = ifelse(conf.high-conf.low>0.9,NA,conf.low), 
                               conf.high = ifelse(conf.high-conf.low>0.9,NA,conf.high)), 
                      aes(y=estimate, ymax=conf.high, ymin=conf.low)) + 
      scale_color_manual(values=set_names(F1.col[2:5],c("K","KH","HK","H")))+
      guides(color="none") +
      scale_y_continuous(ylab, limits=c(0,1), labels=~scales::percent(.,accuracy=1))
  }
  p <- p + scale_x_discrete("Cross", labels = momdadcross.labels, drop=F) +
    theme_minimal()
  print(p)
}

traits %>% filter(generation=="F2") %>% select(data, yvar, ylab, type) %>% 
  pwalk(plot_F2, emm=F2.emm)
```

### Cytonuclear incompatibility

```{r f2plot_contrasts}
F2.contrasts <- tibble(momdadcross = c("H x HK","HK x H","H x KH","KH x H","K x KH","KH x K","K x HK","HK x K"),
                       pair = rep(1:4, each=2),
                       reciprocal.difference = rep(c("not expected", "expected"), times = 2, each = 2))

reorder_momdadcross <- function(df) {
  df %>% filter(momdadcross %in% F2.contrasts$momdadcross) %>% 
    left_join(F2.contrasts, by="momdadcross") %>% 
    mutate(momdadcross = fct_relevel(momdadcross, F2.contrasts$momdadcross)) 
}

plot_F2_contrasts <- function(emm, data, yvar, ylab, type="continuous") {
  data <- get(data) %>% reorder_momdadcross()
  emm <- emm %>% filter(trait==yvar) %>% reorder_momdadcross()
  sig <- F2.mod[[yvar]] %>% 
    multcomp::glht(linfct = multcomp::mcp(momdadcross = F2.contrasts %>% group_by(pair) %>% 
                                            summarize(contrast = paste0("`", paste(momdadcross[1:2], collapse="` - `"),"` == 0")) %>% 
                                            pull(contrast))) %>% summary(test=multcomp::adjusted("none")) %>% tidy() %>% mutate(pair=1:4)
  if(type=="continuous") {
    p <- ggplot(data, aes_string(y=yvar, x="momdadcross")) + 
      geom_violin(aes(fill=reciprocal.difference),draw_quantiles = (1:3)/4) + 
      geom_pointrange(data=emm, aes(y=estimate, ymax=conf.high, ymin=conf.low),color="black", show.legend = F) + 
      scale_fill_manual("Reciprocal difference     :::", values=brewer.pal(10,"Paired")[c(2,8)]) +
      scale_y_continuous(name = ylab, expand = expansion(mult=c(0, 0.05)), limits=c(0,NA))
  } else if(type=="binary") {
    p <- ggplot(data, aes_string(y=yvar, x="momdadcross")) + 
      geom_pointrange(data=emm %>% 
                        mutate(conf.low  = ifelse(conf.high-conf.low>0.9,NA,conf.low), 
                               conf.high = ifelse(conf.high-conf.low>0.9,NA,conf.high)), 
                      aes(y=estimate, ymax=conf.high, ymin=conf.low, color=reciprocal.difference)) + 
      scale_color_manual("Reciprocal difference  :", values=brewer.pal(10,"Paired")[c(2,8)])+
      scale_y_continuous(ylab, limits=c(0,1), labels=~scales::percent(.,accuracy=1))
  }
  ytop = 1.02*max(pull(data, yvar))
  p <- p + scale_x_discrete("Cross", labels = momdadcross.labels) +
    theme_minimal() + theme(legend.position = "top") +
    geom_text(data=sig, aes(x = 2*pair-0.5, y=ytop*1.04, label=ifelse(p.value < 0.01, "< 0.01",round(p.value,2)))) +
    geom_segment(aes(x=2*pair-1, xend=2*pair, y=ytop, yend=ytop))
  print(p)
}

traits %>% filter(generation=="F2", data != "f1seedmass") %>% select(data, yvar, ylab, type) %>% 
  pwalk(plot_F2_contrasts, emm=F2.emm)
```

