---
title: "*Schiedea* seed mass"
author: "[John Powers](http://sites.uci.edu/powers/)"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: no
    lib_dir: libs
    code_folding: hide
    toc: yes
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, message=FALSE}
library(knitr)
knitr::opts_chunk$set(comment="", cache=T, warning = F, message = F, 
                      fig.path = "figures-seedmass/", dev = "svglite", dev.args=list(fix_text_size=FALSE))
library(tidyverse)
theme_set(theme_minimal())
```

```{r mass}
seedmass <- read_csv("data/seedmass.csv") %>% 
  mutate(seed_mass_mg = total_mass_mg / seeds_weighed,
         source = fct_collapse(source, field=c("Field","F"), greenhouse="GH"),
         species = fct_reorder(str_remove(species, "S."), seed_mass_mg),
         habitat = fct_recode(habitat, "dry"="D","mesic"="M","wet"="W"))

#ggplot(seedmass, aes(x=seeds_weighed, y=total_mass_mg)) + geom_point()
ggplot(seedmass, aes(y=species, x=seed_mass_mg, color=source)) + geom_boxplot(outlier.size = 0.3) +
  facet_grid(vars(fct_rev(habitat)),  scales = "free_y", space="free") + 
  labs(color="Source", y="Species", x="Seed mass (mg)")
```

```{r counts}
seedcounts <- read_csv("data/seedcounts.csv", guess_max = 2000) %>% 
  mutate(source = fct_collapse(source, field="Field", greenhouse=c("GH","Source?")),
         species = fct_reorder(str_remove(species, "S.|A. "), viable_seeds),
         habitat = fct_recode(habitat, "dry"="D","mesic"="M","wet"="W"))
ggplot(seedcounts, aes(y=species, x=viable_seeds, color=source)) + geom_boxplot(outlier.size = 0.3) +
  facet_grid(vars(fct_rev(habitat)),  scales = "free_y", space="free") + 
  labs(color="Source", y="Species", x="Viable seeds per capsule")
```

```{r countsmass}
speciesmeans <- seedmass %>% summarize(seed_mass_mg = mean(seed_mass_mg), .by=c(species, habitat)) %>% 
  full_join(seedcounts %>% summarize(viable_seeds = mean(viable_seeds), .by=species)) %>% 
  mutate(seed_mass_per_capsule_mg = seed_mass_mg * viable_seeds)

ggplot(speciesmeans, aes(x = viable_seeds, y=seed_mass_mg, label=species, color=habitat)) + geom_text(fontface=2) + 
  scale_y_log10() + scale_x_log10() + scale_color_discrete() +
  labs(color="Habitat", y="Seed mass (mg)", x="Viable seeds per capsule")
```

```{r phylo, fig.height=6, fig.width=6}
library(phytools)
#from Fig 2, Nuclear BEST tree, Willyard et al. 2011
schtree <- read.nexus("data/fig2.nex") %>% drop.tip("outgroup")
schtree$edge.length=schtree$edge.length/1000
sch<-multi2di(schtree, random=FALSE)
sch$edge.length<-sch$edge.length+0.00001
sch$tip.label <- substr(sch$tip.label,1,4)
sch.p<-drop.tip(sch,setdiff(sch$tip.label, speciesmeans$species))

speciesmeans.log <- speciesmeans[order(match(speciesmeans$species,sch.p$tip.label)),] %>% 
  mutate(viable_seeds=log10(viable_seeds), seed_mass_mg = log10(seed_mass_mg)) 
XY <- as.matrix(speciesmeans.log[,c("viable_seeds", "seed_mass_mg")])
rownames(XY) <- sch.p$tip.label
phylomorphospace(sch.p, XY, node.size=c(0,1.3), xlab="log10 Viable seeds per capsule", ylab="log10 Seed mass (mg)")
points(XY, col=scales::hue_pal()(3)[as.integer(speciesmeans.log$habitat)], pch=19)
legend("bottomright", levels(speciesmeans$habitat), fill = scales::hue_pal()(3), title="Habitat")
```

